<?php

class Countries
{
    private static $list = [
        'AD' => ['ru' => 'Андорра', 'en' => 'Andorra'],
        'AE' => ['ru' => 'ОАЭ', 'en' => 'United Arab Emirates'],
        'AF' => ['ru' => 'Афганистан', 'en' => 'Afghanistan'],
        'AG' => ['ru' => 'Антигуа и Барбуда', 'en' => 'Antigua and Barbuda'],
        'AI' => ['ru' => 'Ангилья', 'en' => 'Anguilla'],
        'AL' => ['ru' => 'Албания', 'en' => 'Albania'],
        'AM' => ['ru' => 'Армения', 'en' => 'Armenia'],
        'AO' => ['ru' => 'Ангола', 'en' => 'Angola'],
        'AQ' => ['ru' => 'Антарктида', 'en' => 'Antarctica'],
        'AR' => ['ru' => 'Аргентина', 'en' => 'Argentina'],
        'AS' => ['ru' => 'Американское Самоа', 'en' => 'American Samoa'],
        'AT' => ['ru' => 'Австрия', 'en' => 'Austria'],
        'AU' => ['ru' => 'Австралия', 'en' => 'Australia'],
        'AW' => ['ru' => 'Аруба', 'en' => 'Aruba'],
        'AX' => ['ru' => 'Аландские острова', 'en' => 'Aland Islands'],
        'AZ' => ['ru' => 'Азербайджан', 'en' => 'Azerbaijan'],
        'BA' => ['ru' => 'Босния и Герцеговина', 'en' => 'Bosnia and Herzegovina'],
        'BB' => ['ru' => 'Барбадос', 'en' => 'Barbados'],
        'BD' => ['ru' => 'Бангладеш', 'en' => 'Bangladesh'],
        'BE' => ['ru' => 'Бельгия', 'en' => 'Belgium'],
        'BF' => ['ru' => 'Буркина Фасо', 'en' => 'Burkina Faso'],
        'BG' => ['ru' => 'Болгария', 'en' => 'Bulgaria'],
        'BH' => ['ru' => 'Бахрейн', 'en' => 'Bahrain'],
        'BI' => ['ru' => 'Бурунди', 'en' => 'Burundi'],
        'BJ' => ['ru' => 'Бенин', 'en' => 'Benin'],
        'BL' => ['ru' => 'Сен-Бартелеми', 'en' => 'Saint-Barthelemy'],
        'BM' => ['ru' => 'Бермуды', 'en' => 'Bermuda'],
        'BN' => ['ru' => 'Бруней', 'en' => 'Brunei'],
        'BO' => ['ru' => 'Боливия', 'en' => 'Bolivia'],
        'BQ' => ['ru' => 'Бонэйр, Синт-Эстатиус и Саба', 'en' => 'Bonaire, Saint Eustatius and Saba'],
        'BR' => ['ru' => 'Бразилия', 'en' => 'Brazil'],
        'BS' => ['ru' => 'Багамские острова', 'en' => 'Bahamas'],
        'BT' => ['ru' => 'Бутан', 'en' => 'Bhutan'],
        'BW' => ['ru' => 'Ботсвана', 'en' => 'Botswana'],
        'BY' => ['ru' => 'Беларусь', 'en' => 'Belarus'],
        'BZ' => ['ru' => 'Белиз', 'en' => 'Belize'],
        'CA' => ['ru' => 'Канада', 'en' => 'Canada'],
        'CC' => ['ru' => 'Кокосовые острова', 'en' => 'Cocos (Keeling) Islands'],
        'CD' => ['ru' => 'Демократическая Республика Конго', 'en' => 'Democratic Republic of the Congo'],
        'CF' => ['ru' => 'Центрально-Африканская Республика', 'en' => 'Central African Republic'],
        'CG' => ['ru' => 'Конго', 'en' => 'Congo'],
        'CH' => ['ru' => 'Швейцария', 'en' => 'Switzerland'],
        'CI' => ['ru' => 'Кот-д’Ивуар', 'en' => 'Cote d\'Ivoire'],
        'CK' => ['ru' => 'Острова Кука', 'en' => 'Cook Islands'],
        'CL' => ['ru' => 'Чили', 'en' => 'Chile'],
        'CM' => ['ru' => 'Камерун', 'en' => 'Cameroon'],
        'CN' => ['ru' => 'Китай', 'en' => 'China'],
        'CO' => ['ru' => 'Колумбия', 'en' => 'Colombia'],
        'CR' => ['ru' => 'Коста-Рика', 'en' => 'Costa Rica'],
        'CU' => ['ru' => 'Куба', 'en' => 'Cuba'],
        'CV' => ['ru' => 'Кабо-Верде', 'en' => 'Cabo Verde'],
        'CW' => ['ru' => 'Кюрасао', 'en' => 'Curacao'],
        'CX' => ['ru' => 'Остров Рождества', 'en' => 'Christmas Island'],
        'CY' => ['ru' => 'Кипр', 'en' => 'Cyprus'],
        'CZ' => ['ru' => 'Чехия', 'en' => 'Czech Republic'],
        'DE' => ['ru' => 'Германия', 'en' => 'Germany'],
        'DJ' => ['ru' => 'Джибути', 'en' => 'Djibouti'],
        'DK' => ['ru' => 'Дания', 'en' => 'Denmark'],
        'DM' => ['ru' => 'Доминика', 'en' => 'Dominica'],
        'DO' => ['ru' => 'Доминиканская республика', 'en' => 'Dominican Republic'],
        'DZ' => ['ru' => 'Алжир', 'en' => 'Algeria'],
        'EC' => ['ru' => 'Эквадор', 'en' => 'Ecuador'],
        'EE' => ['ru' => 'Эстония', 'en' => 'Estonia'],
        'EG' => ['ru' => 'Египет', 'en' => 'Egypt'],
        'ER' => ['ru' => 'Эритрея', 'en' => 'Eritrea'],
        'ES' => ['ru' => 'Испания', 'en' => 'Spain'],
        'ET' => ['ru' => 'Эфиопия', 'en' => 'Ethiopia'],
        'FI' => ['ru' => 'Финляндия', 'en' => 'Finland'],
        'FJ' => ['ru' => 'Фиджи', 'en' => 'Fiji'],
        'FK' => ['ru' => 'Фолклендские острова', 'en' => 'Falkland Islands'],
        'FM' => ['ru' => 'Микронезия', 'en' => 'Federated States of Micronesia'],
        'FO' => ['ru' => 'Фарерские острова', 'en' => 'Faroe Islands'],
        'FR' => ['ru' => 'Франция', 'en' => 'France'],
        'GA' => ['ru' => 'Габон', 'en' => 'Gabon'],
        'GB' => ['ru' => 'Великобритания', 'en' => 'United Kingdom'],
        'GD' => ['ru' => 'Гренада', 'en' => 'Grenada'],
        'GE' => ['ru' => 'Грузия', 'en' => 'Georgia'],
        'GF' => ['ru' => 'Французская Гвинея', 'en' => 'Guyane'],
        'GG' => ['ru' => 'Гернси', 'en' => 'Guernsey'],
        'GH' => ['ru' => 'Гана', 'en' => 'Ghana'],
        'GI' => ['ru' => 'Гибралтар', 'en' => 'Gibraltar'],
        'GL' => ['ru' => 'Гренландия', 'en' => 'Greenland'],
        'GM' => ['ru' => 'Гамбия', 'en' => 'Gambia'],
        'GN' => ['ru' => 'Гвинея', 'en' => 'Guinea'],
        'GP' => ['ru' => 'Гваделупа', 'en' => 'Guadeloupe'],
        'GQ' => ['ru' => 'Экваториальная Гвинея', 'en' => 'Equatorial Guinea'],
        'GR' => ['ru' => 'Греция', 'en' => 'Greece'],
        'GS' => ['ru' => 'Южная Георгия и Южные Сандвичевы острова', 'en' => 'South Georgia and the South Sandwich Islands'],
        'GT' => ['ru' => 'Гватемала', 'en' => 'Guatemala'],
        'GU' => ['ru' => 'Гуам', 'en' => 'Guam'],
        'GW' => ['ru' => 'Гвинея-Бисау', 'en' => 'Guinea-Bissau'],
        'GY' => ['ru' => 'Гайана', 'en' => 'Guyana'],
        'HK' => ['ru' => 'Гонконг', 'en' => 'Hong Kong'],
        'HN' => ['ru' => 'Гондурас', 'en' => 'Honduras'],
        'HR' => ['ru' => 'Хорватия', 'en' => 'Croatia'],
        'HT' => ['ru' => 'Гаити', 'en' => 'Haiti'],
        'HU' => ['ru' => 'Венгрия', 'en' => 'Hungary'],
        'ID' => ['ru' => 'Индонезия', 'en' => 'Indonesia'],
        'IE' => ['ru' => 'Ирландия', 'en' => 'Ireland'],
        'IL' => ['ru' => 'Израиль', 'en' => 'Israel'],
        'IM' => ['ru' => 'Остров Мэн', 'en' => 'Isle of Man'],
        'IN' => ['ru' => 'Индия', 'en' => 'India'],
        'IO' => ['ru' => 'Британская территория в Индийском океане', 'en' => 'British Indian Ocean Territory'],
        'IQ' => ['ru' => 'Ирак', 'en' => 'Iraq'],
        'IR' => ['ru' => 'Иран', 'en' => 'Iran'],
        'IS' => ['ru' => 'Исландия', 'en' => 'Iceland'],
        'IT' => ['ru' => 'Италия', 'en' => 'Italia'],
        'JE' => ['ru' => 'Джерси', 'en' => 'Jersey'],
        'JM' => ['ru' => 'Ямайка', 'en' => 'Jamaica'],
        'JO' => ['ru' => 'Иордания', 'en' => 'Jordan'],
        'JP' => ['ru' => 'Япония', 'en' => 'Japan'],
        'KE' => ['ru' => 'Кения', 'en' => 'Kenya'],
        'KG' => ['ru' => 'Кыргызстан', 'en' => 'Kyrgyzstan'],
        'KH' => ['ru' => 'Камбоджа', 'en' => 'Cambodia'],
        'KI' => ['ru' => 'Кирибати', 'en' => 'Kiribati'],
        'KM' => ['ru' => 'Коморские острова', 'en' => 'Comoros'],
        'KN' => ['ru' => 'Сент-Китс и Невис', 'en' => 'Saint Kitts and Nevis'],
        'KP' => ['ru' => 'Северная Корея', 'en' => 'North Korea'],
        'KR' => ['ru' => 'Южная Корея', 'en' => 'South Korea'],
        'KW' => ['ru' => 'Кувейт', 'en' => 'Kuwait'],
        'KY' => ['ru' => 'Каймановы острова', 'en' => 'Cayman Islands'],
        'KZ' => ['ru' => 'Казахстан', 'en' => 'Kazakhstan'],
        'LA' => ['ru' => 'Лаос', 'en' => 'Laos'],
        'LB' => ['ru' => 'Ливан', 'en' => 'Lebanon'],
        'LC' => ['ru' => 'Святая Люсия', 'en' => 'Saint Lucia'],
        'LI' => ['ru' => 'Лихтенштейн', 'en' => 'Liechtenstein'],
        'LK' => ['ru' => 'Шри-Ланка', 'en' => 'Sri Lanka'],
        'LR' => ['ru' => 'Либерия', 'en' => 'Liberia'],
        'LS' => ['ru' => 'Лесото', 'en' => 'Lesotho'],
        'LT' => ['ru' => 'Литва', 'en' => 'Lithuania'],
        'LU' => ['ru' => 'Люксембург', 'en' => 'Luxembourg'],
        'LV' => ['ru' => 'Латвия', 'en' => 'Latvia'],
        'LY' => ['ru' => 'Ливия', 'en' => 'Libya'],
        'MA' => ['ru' => 'Марокко', 'en' => 'Morocco'],
        'MC' => ['ru' => 'Монако', 'en' => 'Monaco'],
        'MD' => ['ru' => 'Молдова', 'en' => 'Moldova'],
        'ME' => ['ru' => 'Черногория', 'en' => 'Montenegro'],
        'MF' => ['ru' => 'Сен-Мартен', 'en' => 'Saint-Martin'],
        'MG' => ['ru' => 'Мадагаскар', 'en' => 'Madagascar'],
        'MH' => ['ru' => 'Маршалловы острова', 'en' => 'Marshall Islands'],
        'MK' => ['ru' => 'Македония', 'en' => 'Macedonia'],
        'ML' => ['ru' => 'Мали', 'en' => 'Mali'],
        'MM' => ['ru' => 'Мьянма', 'en' => 'Burma'],
        'MN' => ['ru' => 'Монголия', 'en' => 'Mongolia'],
        'MO' => ['ru' => 'Макао', 'en' => 'Macau'],
        'MP' => ['ru' => 'Северные Марианские острова', 'en' => 'Northern Mariana Islands'],
        'MQ' => ['ru' => 'Мартиника', 'en' => 'Martinique'],
        'MR' => ['ru' => 'Мавритания', 'en' => 'Mauritania'],
        'MS' => ['ru' => 'Монтсеррат', 'en' => 'Montserrat'],
        'MT' => ['ru' => 'Мальта', 'en' => 'Malta'],
        'MU' => ['ru' => 'Маврикий', 'en' => 'Mauritius'],
        'MV' => ['ru' => 'Мальдивские острова', 'en' => 'Maldives'],
        'MW' => ['ru' => 'Малави', 'en' => 'Malawi'],
        'MX' => ['ru' => 'Мексика', 'en' => 'Mexico'],
        'MY' => ['ru' => 'Малайзия', 'en' => 'Malaysia'],
        'MZ' => ['ru' => 'Мозамбик', 'en' => 'Mozambique'],
        'NA' => ['ru' => 'Намибия', 'en' => 'Namibia'],
        'NC' => ['ru' => 'Новая Каледония', 'en' => 'Nouvelle-Caledonie'],
        'NE' => ['ru' => 'Нигер', 'en' => 'Niger'],
        'NF' => ['ru' => 'Норфолк', 'en' => 'Norfolk Island'],
        'NG' => ['ru' => 'Нигерия', 'en' => 'Nigeria'],
        'NI' => ['ru' => 'Никарагуа', 'en' => 'Nicaragua'],
        'NL' => ['ru' => 'Нидерланды', 'en' => 'Netherlands'],
        'NO' => ['ru' => 'Норвегия', 'en' => 'Norway'],
        'NP' => ['ru' => 'Непал', 'en' => 'Nepal'],
        'NR' => ['ru' => 'Науру', 'en' => 'Nauru'],
        'NU' => ['ru' => 'Ниуэ', 'en' => 'Niue'],
        'NZ' => ['ru' => 'Новая Зеландия', 'en' => 'New Zealand'],
        'OM' => ['ru' => 'Оман', 'en' => 'Oman'],
        'PA' => ['ru' => 'Панама', 'en' => 'Panama'],
        'PE' => ['ru' => 'Перу', 'en' => 'Peru'],
        'PF' => ['ru' => 'Французская Полинезия', 'en' => 'Polynesie Francaise'],
        'PG' => ['ru' => 'Папуа Новая Гвинея', 'en' => 'Papua New Guinea'],
        'PH' => ['ru' => 'Филиппины', 'en' => 'Philippines'],
        'PK' => ['ru' => 'Пакистан', 'en' => 'Pakistan'],
        'PL' => ['ru' => 'Польша', 'en' => 'Poland'],
        'PM' => ['ru' => 'Сен-Пьер и Микелон', 'en' => 'Saint-Pierre et Miquelon'],
        'PN' => ['ru' => 'Питкэрн', 'en' => 'Pitcairn Islands'],
        'PR' => ['ru' => 'Пуэрто-Рико', 'en' => 'Puerto Rico'],
        'PS' => ['ru' => 'Палестина', 'en' => 'Palestine'],
        'PT' => ['ru' => 'Португалия', 'en' => 'Portugal'],
        'PW' => ['ru' => 'Палау', 'en' => 'Palau'],
        'PY' => ['ru' => 'Парагвай', 'en' => 'Paraguay'],
        'QA' => ['ru' => 'Катар', 'en' => 'Qatar'],
        'RE' => ['ru' => 'Реюньон', 'en' => 'Reunion'],
        'RO' => ['ru' => 'Румыния', 'en' => 'Romania'],
        'RS' => ['ru' => 'Сербия', 'en' => 'Serbia'],
        'RU' => ['ru' => 'Россия', 'en' => 'Russia'],
        'RW' => ['ru' => 'Руанда', 'en' => 'Rwanda'],
        'SA' => ['ru' => 'Саудовская Аравия', 'en' => 'Saudi Arabia'],
        'SB' => ['ru' => 'Соломоновы острова', 'en' => 'Solomon Islands'],
        'SC' => ['ru' => 'Сейшеллы', 'en' => 'Seychelles'],
        'SD' => ['ru' => 'Судан', 'en' => 'Sudan'],
        'SE' => ['ru' => 'Швеция', 'en' => 'Sweden'],
        'SG' => ['ru' => 'Сингапур', 'en' => 'Singapore'],
        'SH' => ['ru' => 'Остров Святой Елены', 'en' => 'Ascension, and Tristan da Cunha Saint Helena'],
        'SI' => ['ru' => 'Словения', 'en' => 'Slovenia'],
        'SJ' => ['ru' => 'Свальбард и Ян-Майен', 'en' => 'Svalbard and Jan Mayen'],
        'SK' => ['ru' => 'Словакия', 'en' => 'Slovakia'],
        'SL' => ['ru' => 'Сьерра-Леоне', 'en' => 'Sierra Leone'],
        'SM' => ['ru' => 'Сан-Марино', 'en' => 'San Marino'],
        'SN' => ['ru' => 'Сенегал', 'en' => 'Senegal'],
        'SO' => ['ru' => 'Сомали', 'en' => 'Somalia'],
        'SR' => ['ru' => 'Суринам', 'en' => 'Suriname'],
        'SS' => ['ru' => 'Южный Судан', 'en' => 'South Sudan'],
        'ST' => ['ru' => 'Сан-Томе и Принсипи', 'en' => 'Sao Tome and Principe'],
        'SV' => ['ru' => 'Сальвадор', 'en' => 'El Salvador'],
        'SX' => ['ru' => 'Синт-Мартен', 'en' => 'Sint Maarten'],
        'SY' => ['ru' => 'Сирия', 'en' => 'Syria'],
        'SZ' => ['ru' => 'Свазиленд', 'en' => 'Swaziland'],
        'TC' => ['ru' => 'Туркс и Кейкос', 'en' => 'Turks and Caicos Islands'],
        'TD' => ['ru' => 'Чад', 'en' => 'Chad'],
        'TF' => ['ru' => 'Французские Южные и Антарктические территории', 'en' => 'Territory of the French Southern and Antarctic Lands'],
        'TG' => ['ru' => 'Того', 'en' => 'Togo'],
        'TH' => ['ru' => 'Таиланд', 'en' => 'Thailand'],
        'TJ' => ['ru' => 'Таджикистан', 'en' => 'Tajikistan'],
        'TK' => ['ru' => 'Токелау', 'en' => 'Tokelau'],
        'TL' => ['ru' => 'Восточный Тимор', 'en' => 'East Timor'],
        'TM' => ['ru' => 'Туркменистан', 'en' => 'Turkmenistan'],
        'TN' => ['ru' => 'Тунис', 'en' => 'Tunisia'],
        'TO' => ['ru' => 'Тонга', 'en' => 'Tonga'],
        'TR' => ['ru' => 'Турция', 'en' => 'Turkey'],
        'TT' => ['ru' => 'Тринидад и Тобаго', 'en' => 'Trinidad and Tobago'],
        'TV' => ['ru' => 'Тувалу', 'en' => 'Tuvalu'],
        'TW' => ['ru' => 'Тайвань', 'en' => 'Taiwan'],
        'TZ' => ['ru' => 'Танзания', 'en' => 'Tanzania'],
        'UA' => ['ru' => 'Украина', 'en' => 'Ukraine'],
        'UG' => ['ru' => 'Уганда', 'en' => 'Uganda'],
        'UM' => ['ru' => 'Внешние малые острова США', 'en' => 'United States Minor Outlying Islands'],
        'US' => ['ru' => 'США', 'en' => 'United States'],
        'UY' => ['ru' => 'Уругвай', 'en' => 'Uruguay'],
        'UZ' => ['ru' => 'Узбекистан', 'en' => 'Uzbekistan'],
        'VA' => ['ru' => 'Ватикан', 'en' => 'Vatican'],
        'VC' => ['ru' => 'Сент-Винсент и Гренадины', 'en' => 'Saint Vincent and the Grenadines'],
        'VE' => ['ru' => 'Венесуэла', 'en' => 'Venezuela'],
        'VG' => ['ru' => 'Британские Виргинские острова', 'en' => 'British Virgin Islands'],
        'VI' => ['ru' => 'Виргинские Острова США', 'en' => 'Virgin Islands of the United States'],
        'VN' => ['ru' => 'Вьетнам', 'en' => 'Vietnam'],
        'VU' => ['ru' => 'Вануату', 'en' => 'Vanuatu'],
        'WF' => ['ru' => 'Уоллис и Футуна', 'en' => 'Wallis and Futuna'],
        'WS' => ['ru' => 'Самоа', 'en' => 'Samoa'],
        'XK' => ['ru' => 'Косово', 'en' => 'Kosovo'],
        'YE' => ['ru' => 'Йемен', 'en' => 'Yemen'],
        'YT' => ['ru' => 'Майотта', 'en' => 'Mayotte'],
        'ZA' => ['ru' => 'ЮАР', 'en' => 'South Africa'],
        'ZM' => ['ru' => 'Замбия', 'en' => 'Zambia'],
        'ZW' => ['ru' => 'Зимбабве', 'en' => 'Zimbabwe'],
    ];

    /**
     * @param bool $en
     * @return array
     */
    public static function getList($en = false)
    {
        $list = [];
        foreach (self::$list as $cc => $names) {
            $list[$cc] = $en ? $names['en'] : $names['ru'];
        }
        return $list;
    }

    /**
     * @param string $cc
     * @param bool $en
     * @return mixed|null
     */
    public static function getName($cc, $en = false)
    {
        $cc = strtoupper($cc);
        return isset(self::$list[$cc]) ? ($en ? self::$list[$cc]['en'] : self::$list[$cc]['ru']) : null;
    }
}
